[keyboard]
name = "xtips_x3s"
product_name = "xtips_x3s"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "RMK"
chip = "stm32f072c8"

[matrix]
input_pins = ["PA0", "PA1", "PA2", "PA3"]
output_pins = ["PB4", "PB5", "PB6", "PB7", "PB8", "PB9", "PB10", "PB11", "PB12", "PB13", "PB14"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, row2col config here is valid ONLY when you're using cloud compilation.
# Checkout doc here: https://rmk.rs/docs/user_guide/faq.html#my-matrix-is-row2col-the-matrix-doesn-t-work
col2row = true

[layout]
rows = 4
cols = 11
layers = 1

matrix_map = """
(0,0) (0,1) (0,2) (0,3) (0,4) (0,5) (0,6) (0,7) (0,8) (0,9) (0,10)
(1,0) (1,1) (1,2) (1,3) (1,4) (1,5) (1,6) (1,7) (1,8) (1,9) (1,10)
(2,0) (2,1) (2,2) (2,3) (2,4) (2,5) (2,6) (2,7) (2,8) (2,9) (2,10)
            (3,0) (3,1) (3,2) (3,3) (3,4) (3,5) (3,6)
"""

[[layer]]
name = "base_layer"
keys = """
  Q  W   E   R   T  Kp1   Y   U   I   O   P
  A  S   D   F   G   Kp2  H   J   K   L   QUOT
  Z  X   C   V   B   Kp3   N  M   COMM  DOT   Kp4
         Kp5   Kp6   Kp7   Kp8   Kp9   LBRC  RBRC
"""

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
#capslock.pin = "PA4r
#capslock.low_active = false
#scrolllock.pin = "PA3"
#scrolllock.low_active = false
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true

[storage]
enabled = false

[dependency]
defmt_log = false

[rmk]
event_channel_size = 2
report_channel_size = 2
vial_channel_size = 1
flash_channel_size = 1
macro_space_size = 8
tap_dance_max_num = 0
fork_max_num = 0
